[package]
name = "serialize_and_deserialize_binary_tree"
version = "0.1.0"
authors = ["cwl <773622153@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
